services:
  live:
    image: ghcr.io/slowlydev/f1-dash-live:latest
    build:
      context: .
      target: live
    restart: always
    ports:
      - 4000:4000
    environment:
      - ORIGIN=${ORIGIN}
      - LIVE_BACKEND_ADDRESS=${LIVE_BACKEND_ADDRESS}
      - RUST_BACKTRACE=${RUST_BACKTRACE}
      - RUST_LOG=${RUST_LOG}
    user: "1000:1000"

  api:
    image: ghcr.io/slowlydev/f1-dash-api:latest
    build:
      context: .
      target: api
    restart: always
    ports:
      - 4001:4001
    environment:
      - ORIGIN=${ORIGIN}
      - API_BACKEND_ADDRESS=${API_BACKEND_ADDRESS}
      - RUST_LOG=${RUST_LOG}
      - RUST_BACKTRACE=${RUST_BACKTRACE}
    user: "1000:1000"

  frontend:
    image: ghcr.io/slowlydev/f1-dash:latest
    build:
      context: ./dash/
      args:
        - LIVE_SOCKET_URL=ws://147.182.132.26:4000
        - API_URL=http://147.182.132.26:4001
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
      - live
    environment:
      - NEXT_PUBLIC_LIVE_SOCKET_URL=ws://147.182.132.26:4000
      - NEXT_PUBLIC_API_URL=http://147.182.132.26:4001
      - NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyC2sLlSxUdDFDQ_iB8POQhBZMqgGXMIYJA
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=racebettingapp.firebaseapp.com
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=racebettingapp
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=racebettingapp.firebasestorage.app
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=759480069787
      - NEXT_PUBLIC_FIREBASE_APP_ID=1:759480069787:web:f98c3f144a034087d1603e
      - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-VLJWPH04M7
    user: "1000:1000"
