version: "3"

services:
  dash:
    build: ./dash/
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_SOCKET_SERVER_URL=ws://backend:4000
      - NEXT_PUBLIC_SERVER_URL=http://backend:4000
  backend:
    build: ./backend/
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgres://devel:devel@database:5432/devel
      - LOG_LEVEL=info
      - BACKEND_ADDRESS=0.0.0.0:4000
    depends_on:
      - database
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=devel
      - POSTGRES_PASSWORD=devel
