version: "3.7"
services:
  f1-dash-postgres:
    container_name: f1-dash-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./pg:/docker-entrypoint-initdb.d/
    env_file:
      - ./docker-compose.env
