FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package.json ./

# Install node modules with npm
RUN npm install

# Copy the rest of the app
COPY . .

# Set non-secret environment variables
ENV SKIP_ENV_VALIDATION=1
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_OPTIONS=--max_old_space_size=2048

# Build the app
RUN npm run build

# Set runtime environment variables
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Expose the port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]