[package]
name = "data-saver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signalrs-client = "0.1.1"
zune-inflate = "0.2.54"
tokio-tungstenite = { version = "0.20.0", features = ["native-tls"] }
reqwest = "0.11.20"
serde = "1.0.188"
serde_json = "1.0"
scylla = "0.9.0"
tokio = { version = "1.12", features = ["full"] }
futures = "0.3.28"
uuid = "1.4.1"
bigdecimal = "0.4.1"
num-bigint = "0.4.4"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
